# Generated by Django 4.0.6 on 2022-09-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
